### ISSUE TITLE
Change Go mod spec to 1.22 from 1.22.0

### ISSUE THREAD

**Issue by grsubramanian** [cedar-policy/cedar-go#17]
We are in the process of incorporating cedar-go into our product.

And we are hitting a snag. Currently, cedar-go specifies a minimum Go version of 1.22.0 in its go.mod file.

Go 1.22.0 seems to have several security vulnerabilities that have since been fixed in higher Go 1.22 versions.

Is it possible to change the Go version for cedar-go in go.mod to 1.22, instead of 1.22.0?

**Comment by 200sc** [comment]
See #18 for discussion.
