### ISSUE TITLE
TinyTodo example in cedar-go

### ISSUE THREAD

**Issue by mqf20** [cedar-policy/cedar-go#24]
I'm trying to rewrite [TinyTodo](https://github.com/cedar-policy/cedar-examples/blob/main/tinytodo) with `cedar-go`.

If this community finds it useful, I'll also submit a PR.

**Comment by mqf20** [comment]
Should the TinyTodo+ + `cedar-go` example be submitted as a PR to this repository or https://github.com/cedar-policy/cedar-examples?

**Comment by andrewmwells-amazon** [comment]
Hi, thanks for the contribution! I think that makes sense a the place to keep it, but let me double check with the team and get back to you.

**Comment by mqf20** [comment]
See https://github.com/cedar-policy/cedar-examples/pull/182
