### ISSUE TITLE
Implement tag based release

### ISSUE THREAD

**Issue by caiorcferreira** [cedar-policy/cedar-go#6]
Go best practice for publishing Go Modules (libraries) is to tag each semantic version. I plan to start a project using `cedar-go` soon and it would be nice to have tagged releases.

Reference: https://go.dev/blog/publishing-go-modules

**Comment by philhassey** [comment]
Thanks @caiorcferreira!  I agree, we'll try and do that by the next release.

**Comment by 200sc** [comment]
I'd propose using a v0 prefixed version until we've reached parity (or near parity) with the Rust implementation. 

Less valuable but if its useful, we can mirror rust within v0 like: rust is at v4.1.2, go is at v0.4.*.

**Comment by philhassey** [comment]
We've started making tagged releases, enjoy!

https://github.com/cedar-policy/cedar-go/releases
